name: Deploy to Firebase Hosting on PR

on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: LearnSpace_IIITA

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies & build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Preview deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADMINLOGIN_5A98A }}
          projectId: adminlogin-5a98a
